# CMake generated Testfile for 
# Source directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/internet-apps/examples
# Build directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/cmake-cache/src/internet-apps/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dhcp-example "ns3.41-dhcp-example-default")
set_tests_properties(ctest-dhcp-example PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/internet-apps/examples/CMakeLists.txt;1;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/internet-apps/examples/CMakeLists.txt;0;")
add_test(ctest-traceroute-example "ns3.41-traceroute-example-default")
set_tests_properties(ctest-traceroute-example PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/internet-apps/examples/CMakeLists.txt;12;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/internet-apps/examples/CMakeLists.txt;0;")
add_test(ctest-ping-example "ns3.41-ping-example-default")
set_tests_properties(ctest-ping-example PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/internet-apps/examples/CMakeLists.txt;25;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/internet-apps/examples/CMakeLists.txt;0;")
