# CMake generated Testfile for 
# Source directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples
# Build directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/cmake-cache/src/netanim/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dumbbell-animation "ns3.41-dumbbell-animation-default")
set_tests_properties(ctest-dumbbell-animation PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-grid-animation "ns3.41-grid-animation-default")
set_tests_properties(ctest-grid-animation PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-star-animation "ns3.41-star-animation-default")
set_tests_properties(ctest-star-animation PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-colors-link-description "ns3.41-colors-link-description-default")
set_tests_properties(ctest-colors-link-description PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-resources-counters "ns3.41-resources-counters-default")
set_tests_properties(ctest-resources-counters PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-wireless-animation "ns3.41-wireless-animation-default")
set_tests_properties(ctest-wireless-animation PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;23;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-uan-animation "ns3.41-uan-animation-default")
set_tests_properties(ctest-uan-animation PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;36;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/netanim/examples/CMakeLists.txt;0;")
