# CMake generated Testfile for 
# Source directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/wimax/examples
# Build directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/cmake-cache/src/wimax/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-wimax-ipv4 "ns3.41-wimax-ipv4-default")
set_tests_properties(ctest-wimax-ipv4 PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/wimax/examples/CMakeLists.txt;1;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/wimax/examples/CMakeLists.txt;0;")
add_test(ctest-wimax-multicast "ns3.41-wimax-multicast-default")
set_tests_properties(ctest-wimax-multicast PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/wimax/examples/CMakeLists.txt;12;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/wimax/examples/CMakeLists.txt;0;")
add_test(ctest-wimax-simple "ns3.41-wimax-simple-default")
set_tests_properties(ctest-wimax-simple PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/wimax/examples/CMakeLists.txt;22;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/wimax/examples/CMakeLists.txt;0;")
