# CMake generated Testfile for 
# Source directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp
# Build directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/cmake-cache/examples/tcp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tcp-large-transfer "ns3.41-tcp-large-transfer-default")
set_tests_properties(ctest-tcp-large-transfer PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;1;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-star-server "ns3.41-tcp-star-server-default")
set_tests_properties(ctest-tcp-star-server PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;10;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-star "ns3.41-star-default")
set_tests_properties(ctest-star PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;19;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-bbr-example "ns3.41-tcp-bbr-example-default")
set_tests_properties(ctest-tcp-bbr-example PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;30;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-bulk-send "ns3.41-tcp-bulk-send-default")
set_tests_properties(ctest-tcp-bulk-send PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;43;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-pcap-nanosec-example "ns3.41-tcp-pcap-nanosec-example-default")
set_tests_properties(ctest-tcp-pcap-nanosec-example PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;52;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-variants-comparison "ns3.41-tcp-variants-comparison-default")
set_tests_properties(ctest-tcp-variants-comparison PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;61;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-pacing "ns3.41-tcp-pacing-default")
set_tests_properties(ctest-tcp-pacing PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;71;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-linux-reno "ns3.41-tcp-linux-reno-default")
set_tests_properties(ctest-tcp-linux-reno PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;81;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-validation "ns3.41-tcp-validation-default")
set_tests_properties(ctest-tcp-validation PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;92;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-dctcp-example "ns3.41-dctcp-example-default")
set_tests_properties(ctest-dctcp-example PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;104;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tcp/CMakeLists.txt;0;")
