# CMake generated Testfile for 
# Source directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial
# Build directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/cmake-cache/examples/tutorial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-hello-simulator "ns3.41-hello-simulator-default")
set_tests_properties(ctest-hello-simulator PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;1;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-first "ns3.41-first-default")
set_tests_properties(ctest-first PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;7;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-second "ns3.41-second-default")
set_tests_properties(ctest-second PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;17;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-third "ns3.41-third-default")
set_tests_properties(ctest-third PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;28;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-fourth "ns3.41-fourth-default")
set_tests_properties(ctest-fourth PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;40;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-fifth "ns3.41-fifth-default")
set_tests_properties(ctest-fifth PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;46;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-sixth "ns3.41-sixth-default")
set_tests_properties(ctest-sixth PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;57;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-seventh "ns3.41-seventh-default")
set_tests_properties(ctest-seventh PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;68;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/tutorial/CMakeLists.txt;0;")
