# CMake generated Testfile for 
# Source directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/nix-vector-routing/examples
# Build directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/cmake-cache/src/nix-vector-routing/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-nix-simple "ns3.41-nix-simple-default")
set_tests_properties(ctest-nix-simple PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nix-simple-multi-address "ns3.41-nix-simple-multi-address-default")
set_tests_properties(ctest-nix-simple-multi-address PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nms-p2p-nix "ns3.41-nms-p2p-nix-default")
set_tests_properties(ctest-nms-p2p-nix PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nix-double-wifi "ns3.41-nix-double-wifi-default")
set_tests_properties(ctest-nix-double-wifi PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/nix-vector-routing/examples/CMakeLists.txt;22;build_lib_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/src/nix-vector-routing/examples/CMakeLists.txt;0;")
