# CMake generated Testfile for 
# Source directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing
# Build directory: /home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/cmake-cache/examples/routing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dynamic-global-routing "ns3.41-dynamic-global-routing-default")
set_tests_properties(ctest-dynamic-global-routing PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;1;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-static-routing-slash32 "ns3.41-static-routing-slash32-default")
set_tests_properties(ctest-static-routing-slash32 PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;11;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-global-routing-slash32 "ns3.41-global-routing-slash32-default")
set_tests_properties(ctest-global-routing-slash32 PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;21;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-global-injection-slash32 "ns3.41-global-injection-slash32-default")
set_tests_properties(ctest-global-injection-slash32 PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;31;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-global-routing "ns3.41-simple-global-routing-default")
set_tests_properties(ctest-simple-global-routing PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;41;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-alternate-routing "ns3.41-simple-alternate-routing-default")
set_tests_properties(ctest-simple-alternate-routing PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;51;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-mixed-global-routing "ns3.41-mixed-global-routing-default")
set_tests_properties(ctest-mixed-global-routing PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;60;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-routing-ping6 "ns3.41-simple-routing-ping6-default")
set_tests_properties(ctest-simple-routing-ping6 PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;70;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-manet-routing-compare "ns3.41-manet-routing-compare-default")
set_tests_properties(ctest-manet-routing-compare PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;79;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-ripng-simple-network "ns3.41-ripng-simple-network-default")
set_tests_properties(ctest-ripng-simple-network PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;93;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-rip-simple-network "ns3.41-rip-simple-network-default")
set_tests_properties(ctest-rip-simple-network PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;102;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-global-routing-multi-switch-plus-router "ns3.41-global-routing-multi-switch-plus-router-default")
set_tests_properties(ctest-global-routing-multi-switch-plus-router PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;111;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-multicast-flooding "ns3.41-simple-multicast-flooding-default")
set_tests_properties(ctest-simple-multicast-flooding PROPERTIES  WORKING_DIRECTORY "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build/examples/routing/" _BACKTRACE_TRIPLES "/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;126;build_example;/home/pham-dinh-chien/ns-allinone-3.41/ns-3.41/examples/routing/CMakeLists.txt;0;")
